name: gh-ci
on:
  pull_request
jobs:
  test_sdformat_urdf:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ros-distro: ["rolling"]
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros-distro }}
      - name: Build and test all packages
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros-distro }}
